name: openlist_utils
description: "OpenListApp utils"
version: 0.0.1+2
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  jaguar: ^3.1.4
  jaguar_flutter_asset: ^3.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  tdesign_flutter: ^0.2.0
  openlist_config:
    path: ../openlist_config
  openlist_background_service:
    path: ../openlist_background_service
  openlist_api:
    path: ../openlist_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
