name: openlistapp
version: 1.0.0.1
summary: OpenList App
description: AList or OpenList App

confinement: strict
base: core22
grade: stable

apps:
  openiothub:
    command: openlist
    extensions: [gnome]
    plugs:
      - network
      - network-bind
parts:
  openiothub:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
