name: openlist_background_service publish

on:
  push:
    tags: ["openlist_background_service-v*"]

jobs:
  publish:
    name: Publish openlist_background_service on pub.dev
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      # 下载除iOS、macOS以外的库并发布
      - uses: robinraju/release-downloader@v1
        with:
          repository: 'OpenListApp/OpenListLib'
          latest: true
          fileName: 'mobile.aar'
          out-file-path: 'openlist_background_service/android/libs'
      - uses: robinraju/release-downloader@v1
        with:
          repository: 'OpenListApp/OpenListLib'
          latest: true
          fileName: 'libmobile_amd64.so'
          out-file-path: 'openlist_background_service/linux/libs'
      - run: mv openlist_background_service/linux/libs/libmobile_amd64.so openlist_background_service/linux/libs/libmobile.so
      - uses: robinraju/release-downloader@v1
        with:
          repository: 'OpenListApp/OpenListLib'
          latest: true
          fileName: 'mobile_amd64.dll'
          out-file-path: 'openlist_background_service/windows/libs'
      - run: mv openlist_background_service/windows/libs/mobile_amd64.dll openlist_background_service/windows/libs/mobile.dll
      # This step adds the auth token for pub.dev
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Publish to pub.dev
        id: pub_release
        uses: leancodepl/mobile-tools/.github/actions/pub-release@pub-release-v1
        with:
          path: openlist_background_service
